### ISSUE TITLE
pdf generation via html string doesn't work

### ISSUE THREAD

**Issue by gitawego** [traviscooper/node-wkhtml#1]
I tried to create  a pfd vis a html string such as 

<pre>
<p>hell world!</p>
</pre>

but it doesn't work.

the command line generated is 

<pre>
echo <p>Hello World</p> | wkhtmltopdf - -
</pre>

**Comment by gitawego** [comment]
it throws error:  Command failed: /bin/sh: Syntax error: "|" unexpected

**Comment by mhemesath** [comment]
I think I see the bug. I'll push a fix once I have internet access for my computer in a few hours.

**Comment by gitawego** [comment]
thank you very much :)

**Comment by mhemesath** [comment]
This issue should be resolved now. Let me know if you have any other issues.

Thanks!

**Comment by gitawego** [comment]
yes, it works. thanks very much!
