### ISSUE TITLE
Take on node-wkhtml for legacy maintenance

### ISSUE THREAD

**Issue by traviscooper** [traviscooper/node-wkhtml#13]
Hi Mike, I'd be happy to take this repo, so that we can have it around for legacy purposes.

**Comment by mhemesath** [comment]
Done! I'll transfer the repo to you and tomorrow take a look at transferring the NPM stuff.

**Comment by mhemesath** [comment]
Heads up,  you have to delete your fork before I can transfer it to you.

**Comment by traviscooper** [comment]
Just deleted the fork. Thanks Mike!
